# Generated by Django 3.1.4 on 2020-12-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('curr_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('game_map', models.CharField(max_length=148)),
                ('server_ip', models.GenericIPAddressField(unique=True)),
                ('server_port', models.IntegerField()),
            ],
        ),
    ]
