# Generated by Django 3.1.4 on 2020-12-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='id',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='server_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
